### ISSUE TITLE
Dynamic images caching

### ISSUE THREAD

**Issue by Ratatinator97** [Pictalk-speech-made-easy/pictranslate#15]

**Comment by Vishnudas2003** [comment]
Hello, 
I want to work on this Issue, Is this still available ?
Thank you

**Comment by Ratatinator97** [comment]
@Vishnudas2003 Hello !
Sorry, I didn't saw your message on time ! If you want to improve the the caching mecanism, feel free to make a pull request... 
If you want to help us further for the other applications, don't hesitate to send me an email or reply to this message.
